### PR TITLE
Dynamically determine if a file 'isKubernetes' based on filetype and 'Kind's in the cluster

### PR DESCRIPTION
**Pull request by reavessm**
NOTE: This currently makes an API call every time you open a file.  It will need to refactored to save the table of filetypes to disk somwhere

This should get rid of `Matches multiple schemas when only one must validate.` for files like `foo.deployment.yaml`.

### CODE REVIEW

**Comment by diogo464** [comment]
I can't reproduce that error. If I create a `foo.deployment.yaml` with a basic deployment I get  proper autocompletion.
<details>
<summary>foo.deployment.yaml</summary>

```yaml
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: name
spec:
  selector:
    matchLabels:
      app: name
  template:
    metadata:
      labels:
        app: name
    spec:
      containers:
        - name: name
          image: docker.io/alpine:latest
```

</details>

That error usually happens if the yamlls server patch is not working.
If everything is working properly then yamlls will generate that error but in case the file in question is a "Kubernetes File" it will just ignore it. The problem that the patch tries to solve is that the definition of a "Kubernetes File" is hardcoded and to workaround that it simply ignores that error for every yaml file.

Try to check if the patch is applied by running: `:KubernetesIsYamllsPatched`, it should print `true`.

You can see in the [source of yaml](https://github.com/redhat-developer/yaml-language-server/blob/ed03cbf71ade29ea62b4bcac0d8952195fd6969d/src/languageservice/services/yamlValidation.ts#L122s) that it only ignores the `MATCHES_MULTIPLE` error when the file is `isKubernetes`.
The patch just removes that check for `isKubernetes` and ignores the error for any file.

**Comment by reavessm** [comment]
It turns out my yamlls is not patched, however the yamlls allows to set the kubernetes flag so personally I'd rather set it that way.  Plus I think its nice to only enable yamlls on the correct filetypes.  If you do something like:

```lua
  yamlls = {
    yaml = {
      schemas = {
        [require('kubernetes').yamlls_schema()] = require('kubernetes').yamlls_filetypes()
      }
    }
  }
```

Then files like `docker-compose.yml` are excluded.

**Comment by diogo464** [comment]
Yes, I can see that being a problem with `docker-compose.yml` and others, but I don't know how to fix it.

What do you mean by?
>  the yamlls allows to set the kubernetes flag

And I am not sure `require('kubernetes').yamlls_filetypes()` would fix it because I don't think the convention `*.<kind>.yaml` is used a lot, at least I don't use it personally and I also don't usually see it out in open.

I think it could be added as a helper function for people that use that convention but it wouldn't fix the problem.

**Comment by reavessm** [comment]
The yamlls docs show setting yaml.schema.kubernetes:

https://github.com/redhat-developer/yaml-language-server/tree/ed03cbf71ade29ea62b4bcac0d8952195fd6969d#more-examples-of-schema-association

Setting this to the filetypes fixes my issue even though my yamlls is NOT patched.

And for the file convention of `*.<kind>.yaml`, I'm not sure how common it is, but we use it a fair bit at work.  Apparently it's an older standard?  Vim used to have documentation on so-called "dotted file types", but that documentation is hard to find now-a-days

**Comment by diogo464** [comment]
> The yamlls docs show setting yaml.schema.kubernetes:

That is the hardcoded part, if you notice, all other schemas have a url to some file but in the case of kubernetes its just "kubernetes", that is what causes yamlls to set the flag `isKubernetes` and it also uses a [hard coded schema](https://github.com/redhat-developer/yaml-language-server/blob/ed03cbf71ade29ea62b4bcac0d8952195fd6969d/src/languageservice/utils/schemaUrls.ts#L8).
That hard coded schema doesn't support CRDs that is why we need to generate a schema using the data from the cluster.
The vscode plugin does something similar, if you have the kubernetes extension you will get prompted to fetch CRDs from your cluster so that it can support them. But the lsp is better integrated with vscode, this is mostly a hack to get things working.

> Setting this to the filetypes fixes my issue even though my yamlls is NOT patched.

The reason it works even tough its not patched is probably because the `Deployment` is present in the default schema, but if you try to use some other custom CRD it probably won't work.

**Comment by reavessm** [comment]
So I was able to get the patch working.  I forgot to call:

```lua
  config = function()
    require("kubernetes").setup()
  end
```

Having a set up in my `init.lua` that looks like

```lua
  yamlls = {
    yaml = {
      schemas = {
        [require('kubernetes').yamlls_schema()] = require('kubernetes').yamlls_filetypes()
      }
    }
  }
```

allows me to get CRD defintions for files like `apps.argocd.yml` but it'll leave all of my other yaml files alone.

image

**Comment by diogo464** [comment]
I updated the README and formated the code. Do you want to merge this @reavessm ?

**Pull request merged**
